export const data: any[] = [
  {
    "id": 1,
    "name": "audit",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "Filter",
    "michael": "Rate-Limit",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 2,
    "name": "auditTime",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "Filter",
    "michael": "Rate-Limit",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 3,
    "name": "buffer",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Buffering",
    "oldSchool": "Transformation",
    "michael": "Buffer",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 4,
    "name": "bufferCount",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Buffering",
    "oldSchool": "Transformation",
    "michael": "Buffer",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 5,
    "name": "bufferTime",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Buffering",
    "oldSchool": "Transformation",
    "michael": "Buffer",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 6,
    "name": "bufferToggle",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Buffering",
    "oldSchool": "Transformation",
    "michael": "Buffer",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 7,
    "name": "bufferWhen",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Buffering",
    "oldSchool": "Transformation",
    "michael": "Buffer",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 8,
    "name": "catchError",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "ErrorHandling",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 9,
    "name": "combineAll",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Combining",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 10,
    "name": "combineLatest",
    "isDeprecated": "Yes",
    "isAlias": "No",
    "cedric": "Combining",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 11,
    "name": "concat",
    "isDeprecated": "Yes",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Combination",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 12,
    "name": "concatAll",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Combination",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 13,
    "name": "concatMap",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Transformation",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 14,
    "name": "concatMapTo",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Transformation",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 15,
    "name": "count",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Reducing",
    "oldSchool": "None",
    "michael": "Scan",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 16,
    "name": "debounce",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "Filter",
    "michael": "Rate-Limit",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 17,
    "name": "debounceTime",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "Filter",
    "michael": "Rate-Limit",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 18,
    "name": "defaultIfEmpty",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "Conditional",
    "michael": "Condition",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 19,
    "name": "delay",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Delaying",
    "oldSchool": "Utility",
    "michael": "Timing",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 20,
    "name": "delayWhen",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Delaying",
    "oldSchool": "Utility",
    "michael": "Timing",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 21,
    "name": "dematerialize",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "Utility",
    "michael": "Transform",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 22,
    "name": "distinct",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Filtering",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 23,
    "name": "distinctUntilChanged",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Filtering",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 24,
    "name": "distinctUntilKeyChanged",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Filtering",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 25,
    "name": "elementAt",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Finding",
    "oldSchool": "None",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 26,
    "name": "endWith",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 27,
    "name": "every",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Conditional",
    "oldSchool": "Conditional",
    "michael": "Scan",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 28,
    "name": "exhaust",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Converting",
    "oldSchool": "Combination",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 29,
    "name": "exhaustMap",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Flattening",
    "oldSchool": "Transformation",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 30,
    "name": "expand",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Flattening",
    "oldSchool": "Transformation",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 31,
    "name": "filter",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Flattening",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 32,
    "name": "finalize",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "Utility",
    "michael": "Side-Effect",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 33,
    "name": "find",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Finding",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 34,
    "name": "findIndex",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Finding",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 35,
    "name": "first",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 36,
    "name": "groupBy",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "Transformation",
    "michael": "Slice",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 37,
    "name": "ignoreElements",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Flattening",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 38,
    "name": "isEmpty",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Conditional",
    "oldSchool": "None",
    "michael": "Condition",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 39,
    "name": "last",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 40,
    "name": "map",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Mapping",
    "oldSchool": "Transformation",
    "michael": "Transform",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 41,
    "name": "mapTo",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Mapping",
    "oldSchool": "Transformation",
    "michael": "Transform",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 42,
    "name": "materialize",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "None",
    "michael": "Transform",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 43,
    "name": "max",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Reducing",
    "oldSchool": "None",
    "michael": "Scan",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 44,
    "name": "merge",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Combination",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 45,
    "name": "mergeAll",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Converting",
    "oldSchool": "Combination",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 46,
    "name": "mergeMap",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Flattening",
    "oldSchool": "Transformation",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 47,
    "name": "flatMap",
    "isDeprecated": "No",
    "isAlias": "Yes",
    "cedric": "Flattening",
    "oldSchool": "Transformation",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 48,
    "name": "mergeMapTo",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Flattening",
    "oldSchool": "Transformation",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 49,
    "name": "mergeScan",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Scanning",
    "oldSchool": "None",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 50,
    "name": "min",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Reducing",
    "oldSchool": "None",
    "michael": "Scan",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 51,
    "name": "multicast",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Sharing",
    "oldSchool": "Multicasting",
    "michael": "Multicast",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 52,
    "name": "observeOn",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "None",
    "michael": "Scheduling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 53,
    "name": "onErrorResumeNext",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "None",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 54,
    "name": "pairwise",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Scanning",
    "oldSchool": "Combination",
    "michael": "Buffer",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 55,
    "name": "partition",
    "isDeprecated": "Yes",
    "isAlias": "No",
    "cedric": "Filtering",
    "oldSchool": "Transformation",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 56,
    "name": "pluck",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Mapping",
    "oldSchool": "Transformation",
    "michael": "Transform",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 57,
    "name": "publish",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Sharing",
    "oldSchool": "Multicasting",
    "michael": "Multicast",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 58,
    "name": "publishBehavior",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Sharing",
    "oldSchool": "None",
    "michael": "Multicast",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 59,
    "name": "publishLast",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Sharing",
    "oldSchool": "None",
    "michael": "Multicast",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 60,
    "name": "publishReplay",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Sharing",
    "oldSchool": "None",
    "michael": "Multicast",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 61,
    "name": "race",
    "isDeprecated": "Yes",
    "isAlias": "No",
    "cedric": "Combining",
    "oldSchool": "Combination",
    "michael": "Condition",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 62,
    "name": "reduce",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Reducing",
    "oldSchool": "Mathematical and Aggregate",
    "michael": "Scan",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 63,
    "name": "repeat",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "Utility",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 64,
    "name": "repeatWhen",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "None",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 65,
    "name": "retry",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "ErrorHandling",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 66,
    "name": "retryWhen",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "ErrorHandling",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 67,
    "name": "refCount",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Sharing",
    "oldSchool": "None",
    "michael": "Multicast",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 68,
    "name": "sample",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "None",
    "michael": "Rate-Limit",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 69,
    "name": "sampleTime",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "Filter",
    "michael": "Rate-Limit",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 70,
    "name": "scan",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Scanning",
    "oldSchool": "Transformation",
    "michael": "Scan",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 71,
    "name": "sequenceEqual",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Conditional",
    "oldSchool": "Conditional",
    "michael": "Scan",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 72,
    "name": "share",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Sharing",
    "oldSchool": "Multicasting",
    "michael": "Multicast",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 73,
    "name": "shareReplay",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Sharing",
    "oldSchool": "Multicasting",
    "michael": "Multicast",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 74,
    "name": "single",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Flattening",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 75,
    "name": "skip",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 76,
    "name": "skipLast",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 77,
    "name": "skipUntil",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 78,
    "name": "skipWhile",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 79,
    "name": "startWith",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 80,
    "name": "subscribeOn",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "None",
    "michael": "Scheduling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 81,
    "name": "switchAll",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 82,
    "name": "switchMap",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 83,
    "name": "switchMapTo",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Merge",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 84,
    "name": "switchScan",
    "isDeprecated": "",
    "isAlias": "",
    "cedric": "",
    "oldSchool": "",
    "michael": "Combine",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 85,
    "name": "take",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 86,
    "name": "takeLast",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 87,
    "name": "takeUntil",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 88,
    "name": "takeWhile",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Slicing",
    "oldSchool": "Filter",
    "michael": "Filter",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 89,
    "name": "tap",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "Utility",
    "michael": "Side-Effect",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 90,
    "name": "throttle",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "Filter",
    "michael": "Rate-Limit",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 91,
    "name": "throttleTime",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Rate-limiting",
    "oldSchool": "Filter",
    "michael": "Rate-Limit",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 92,
    "name": "throwIfEmpty",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "ErrorHandling",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 93,
    "name": "timeInterval",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "None",
    "michael": "Transform",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 94,
    "name": "timeout",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "Utility",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 95,
    "name": "timeoutWith",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "None",
    "michael": "Error-Handling",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 96,
    "name": "timestamp",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Misc",
    "oldSchool": "None",
    "michael": "Transform",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 97,
    "name": "toArray",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Reducing",
    "oldSchool": "Transformation",
    "michael": "Scan",
    "isOperator": "operator",
    "hoo": "FirstOrder"
  },
  {
    "id": 98,
    "name": "window",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Windowing",
    "oldSchool": "Transformation",
    "michael": "Slice",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 99,
    "name": "windowCount",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Windowing",
    "oldSchool": "Transformation",
    "michael": "Slice",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 100,
    "name": "windowTime",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Windowing",
    "oldSchool": "Transformation",
    "michael": "Slice",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 101,
    "name": "windowToggle",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Windowing",
    "oldSchool": "Transformation",
    "michael": "Slice",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 102,
    "name": "windowWhen",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Windowing",
    "oldSchool": "Transformation",
    "michael": "Slice",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 103,
    "name": "withLatestFrom",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Combining",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 104,
    "name": "zip",
    "isDeprecated": "Yes",
    "isAlias": "No",
    "cedric": "Combining",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 105,
    "name": "zipAll",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Converting",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "operator",
    "hoo": "HigherOrder"
  },
  {
    "id": 106,
    "name": "AsyncSubject",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Subject",
    "michael": "Subject",
    "isOperator": "static",
    "hoo": "None"
  },
  {
    "id": 107,
    "name": "BehaviorSubject",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Subject",
    "michael": "Subject",
    "isOperator": "static",
    "hoo": "None"
  },
  {
    "id": 108,
    "name": "combineLatest",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Combining",
    "oldSchool": "None",
    "michael": "Combine",
    "isOperator": "static",
    "hoo": "HigherOrder"
  },
  {
    "id": 109,
    "name": "concat",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Combination",
    "michael": "Merge",
    "isOperator": "static",
    "hoo": "HigherOrder"
  },
  {
    "id": 110,
    "name": "create (Observable.create)",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 111,
    "name": "defer",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 112,
    "name": "EMPTY",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 113,
    "name": "forkJoin",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Combining",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "static",
    "hoo": "HigherOrder"
  },
  {
    "id": 114,
    "name": "from",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 115,
    "name": "fromEvent",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 116,
    "name": "fromEventPattern",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 117,
    "name": "generate",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "None",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 118,
    "name": "iif",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Conditional",
    "michael": "Condition",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 119,
    "name": "interval",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Timing",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 120,
    "name": "merge",
    "isDeprecated": "Yes",
    "isAlias": "No",
    "cedric": "Merging",
    "oldSchool": "Combination",
    "michael": "Merge",
    "isOperator": "static",
    "hoo": "HigherOrder"
  },
  {
    "id": 121,
    "name": "NEVER",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "None",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 122,
    "name": "of",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 123,
    "name": "onErrorResumeNext",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "None",
    "michael": "Error-Handling",
    "isOperator": "static",
    "hoo": "HigherOrder"
  },
  {
    "id": 124,
    "name": "pairs",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "None",
    "michael": "Transform",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 125,
    "name": "race",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "None",
    "michael": "Condition",
    "isOperator": "static",
    "hoo": "HigherOrder"
  },
  {
    "id": 126,
    "name": "range",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Creation",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 127,
    "name": "ReplaySubject",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Subject",
    "michael": "Subject",
    "isOperator": "static",
    "hoo": "None"
  },
  {
    "id": 128,
    "name": "Subject",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Subject",
    "michael": "Subject",
    "isOperator": "static",
    "hoo": "None"
  },
  {
    "id": 129,
    "name": "throwError",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Error-Handling",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 130,
    "name": "timer",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "Creation",
    "michael": "Timing",
    "isOperator": "static",
    "hoo": "FirstOrder"
  },
  {
    "id": 131,
    "name": "zip",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "Combining",
    "oldSchool": "Combination",
    "michael": "Combine",
    "isOperator": "static",
    "hoo": "HigherOrder"
  },
  {
    "id": 132,
    "name": "scheduled",
    "isDeprecated": "No",
    "isAlias": "No",
    "cedric": "None",
    "oldSchool": "None",
    "michael": "Scheduling",
    "isOperator": "static",
    "hoo": "FirstOrder"
  }
];
